"""link table

Revision ID: 43919b0ab3f3
Revises: b9001ac20450
Create Date: 2024-06-19 00:54:26.612717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43919b0ab3f3'
down_revision = 'b9001ac20450'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('link',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('link', sa.String(length=256), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_link_category_id'), ['category_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_link_category_id'))

    op.drop_table('link')
    # ### end Alembic commands ###
